version: "3.1"

services:
  zookeeper:
    image: zookeeper:latest
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092